image: gcc

before_script:
    - apt-get update -y

stages:
    - build
    - test
    - lint

build:
    stage: build
    script:
        - apt-get install libgtest-dev -y
        - make
    artifacts:
        paths:
            - hangman

test:
    stage: test
    script:
        - apt-get install libgtest-dev -y
        - apt-get install python3-pip -y
        - apt-get install cmake -y
        - pip3 install gcovr
        - make test

lint:
    stage: lint
    script:
        - apt-get install clang-format -y
        - make lint
