image: gcc

before_script:
    - apt-get update && apt-get install python3-pip && pip3 install cpplint

build:
  stage: build
  script:
    - cpplint main.cpp Word.h Word.cpp
    - make
  artifacts:
    paths:
      - gallow

# run tests using the binary built before
#test:
  #stage: test
  #script:
   # - ./runmytests.sh
