image: gcc

before_script:
    - apt-get update
    - apt-get install python3-pip -y
    - apt-get install clang-format -y
    - apt-get install clang-tidy -y
    - apt-get install libgtest-dev -y
    - apt-get install cmake -y
    - pip3 install gcovr

lint:
  script:
    - make lint

test:
  script:
    - make test

build:
  stage: build
  script:
    - make
  artifacts:
    paths:
      - hangman
